## Bag Of word

In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam'] = df['Category'].map({'ham':0,'spam':1})

In [15]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [23]:
x_train.shape

(4457,)

In [27]:
y_train

5535    0
4982    0
4861    0
3004    0
3380    0
       ..
3516    0
3869    0
4790    0
4254    0
5441    0
Name: spam, Length: 4457, dtype: int64

In [31]:
x_train

5535    I know you are thinkin malaria. But relax, chi...
4982                               I said its okay. Sorry
4861    Response is one of d powerful weapon 2 occupy ...
3004                           I will see in half an hour
3380                      Dear umma she called me now :-)
                              ...                        
3516                     I'm job profile seems like bpo..
3869    not that I know of, most people up here are st...
4790    We're on the opposite side from where we dropp...
4254    Juz now havent woke up so a bit blur blur... C...
5441    By the way, make sure u get train to worc fore...
Name: Message, Length: 4457, dtype: object

In [37]:
type(x_train.values)

numpy.ndarray

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_cv  = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58794 stored elements and shape (4457, 7702)>

In [43]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
x_train_cv.shape

(4457, 7702)

### 7072 unique word`

In [54]:
v.get_feature_names_out()[1000:1050]

array(['applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'appropriate', 'approve', 'approved', 'approx',
       'apps', 'appt', 'april', 'aproach', 'aquarius', 'ar', 'arabian',
       'archive', 'ard', 'are', 'area', 'aren', 'arent', 'aretaking',
       'areyouunique', 'argentina', 'argh', 'argue', 'argument', 'aries',
       'arise', 'arises', 'arm', 'armand', 'armenia', 'arms', 'arng',
       'arngd', 'arnt', 'around', 'aroundn', 'arr', 'arrange',
       'arranging', 'arrested', 'arrival', 'arrive', 'arrived', 'arrow',
       'arsenal', 'art'], dtype=object)

In [56]:
v.vocabulary_

{'know': 3911,
 'you': 7666,
 'are': 1018,
 'thinkin': 6802,
 'malaria': 4276,
 'but': 1552,
 'relax': 5628,
 'children': 1760,
 'cant': 1619,
 'handle': 3281,
 'she': 6029,
 'would': 7576,
 'have': 3325,
 'been': 1259,
 'worse': 7568,
 'and': 935,
 'its': 3723,
 'gastroenteritis': 3044,
 'if': 3563,
 'takes': 6648,
 'enough': 2571,
 'to': 6890,
 'replace': 5666,
 'her': 3379,
 'loss': 4162,
 'temp': 6717,
 'will': 7486,
 'reduce': 5600,
 'give': 3105,
 'meds': 4370,
 'now': 4793,
 'just': 3827,
 'vomit': 7283,
 'self': 5959,
 'limiting': 4072,
 'illness': 3575,
 'has': 3313,
 'which': 7459,
 'means': 4361,
 'in': 3599,
 'few': 2781,
 'days': 2137,
 'it': 3716,
 'completely': 1904,
 'stop': 6439,
 'said': 5834,
 'okay': 4866,
 'sorry': 6276,
 'response': 5700,
 'is': 3705,
 'one': 4890,
 'of': 4842,
 'powerful': 5291,
 'weapon': 7384,
 'occupy': 4835,
 'place': 5175,
 'others': 4951,
 'heart': 3350,
 'so': 6230,
 'always': 907,
 'who': 7463,
 'cares': 1639,
 'gud': 3230,
 'night': 4726

In [58]:
x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [66]:
np.where(x_train_np[0] != 0)

(array([ 935, 1018, 1259, 1552, 1619, 1760, 1904, 2137, 2571, 2781, 3044,
        3105, 3281, 3313, 3325, 3379, 3563, 3575, 3599, 3716, 3723, 3827,
        3911, 4072, 4162, 4276, 4361, 4370, 4793, 5600, 5628, 5666, 5959,
        6029, 6439, 6648, 6717, 6802, 6890, 7283, 7459, 7486, 7568, 7576,
        7666]),)

In [76]:
x_train[:4][5535]

'I know you are thinkin malaria. But relax, children cant handle malaria. She would have been worse and its gastroenteritis. If she takes enough to replace her loss her temp will reduce. And if you give her malaria meds now she will just vomit. Its a self limiting illness she has which means in a few days it will completely stop'

In [78]:
x_train_np[0][935]

np.int64(2)

In [80]:
from sklearn.naive_bayes import MultinomialNB

In [82]:
model = MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [84]:
x_test_cv = v.transform(x_test)

In [86]:
from sklearn.metrics import classification_report

In [90]:
y_pred = model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       948
           1       0.99      0.92      0.95       167

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [92]:
emails = [
    'Hey mohan ca we get together to watch football game tommorow?',
    'Upto 20% discount on parking, exclusive offer just for you, Dont miss the reward!'
]

In [94]:
email_count = v.transform(emails)
model.predict(email_count)

array([0, 1])